# The kubernetes deployment for the details v2 application.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: details-v2
  namespace: bookinfo
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        # Tell Prometheus to scrape the application's metrics.
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "9080"
        kiali.io/runtimes: "go,go-bookinfo-details"
      labels:
        app: details
        version: v2
    spec:
      containers:
      - name: details
        image: quay.io/simonpasquier/go-bookinfo-details:latest
        imagePullPolicy: Always
        args:
        - -listen-address
        - :9080
        # cache responses to avoid rate-limiting.
        - -cache-expiry
        - 10s
        ports:
        - containerPort: 9080
---
