{
 "title": "details service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Incoming requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(details_incoming_requests_duration_seconds_count[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(details_incoming_requests_duration_seconds_count{code=~\"5.+\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(details_incoming_requests_duration_seconds_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (job, le) (rate(details_incoming_requests_duration_seconds_bucket[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(1, sum by (job, le) (rate(details_incoming_requests_duration_seconds_bucket[5m])))",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Outgoing requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(details_outgoing_requests_duration_seconds_count[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(details_outgoing_requests_duration_seconds_count{code=~\"5.+\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(details_outgoing_requests_duration_seconds_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (job, le) (rate(details_outgoing_requests_duration_seconds_bucket[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(1, sum by (job, le) (rate(details_outgoing_requests_duration_seconds_bucket[5m])))",
     "legendFormat": "max"
    },
    {}
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"details\"}[5m])*100",
     "legendFormat": " {{ pod_name }} ({{ version }})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"details\"}",
     "legendFormat": " {{ pod_name }} ({{ version }})"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app=\"details\"}[5m])",
     "legendFormat": " {{ pod_name }} ({{ version }})"
    }
   ]
  }
 ]
}